services:
    redis:
        image: redis:7.4-alpine
        container_name: redis-db
        ports:
            - "6379:6379"
        volumes:
            - redis-data:/data
        command: redis-server --appendonly yes

volumes:
    redis-data:
